//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialChatDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_message
    {
        public int id { get; set; }
        public string author { get; set; }
        public string message { get; set; }
    }
}
